### ISSUE TITLE
Fragment of the data written again after the real end of the data

### ISSUE THREAD

**Issue by hadrianw** [cloudflare/lol-html#111] opened 2021-12-10 20:09 UTC
I do not do any rewrites at all, so I expect the output to be the same as the input. However the output has a fragment that is repeated just after the end of the input. Simplifying - every letter represents part of the input: I give it "abcde" and I get "abcdecd".

You can get the test code from here: https://github.com/hadrianw/slimpipe

I run this code:
```
extern crate chardetng;
extern crate lol_html;

use std::fs::File;
use std::io::{Read, Write};
use std::cmp;
use chardetng::EncodingDetector;
use lol_html::{AsciiCompatibleEncoding, HtmlRewriter, Settings};

fn main() {
    let mut buf = [0u8; 8192];
    let mut file = File::open("simple.html").unwrap();
    let mut size = file.read(&mut buf).unwrap();

    let mut det = EncodingDetector::new();
    det.feed(&buf[..cmp::min(1024, size)], false);
    let enc = det.guess(Some(b"com"), false);
    let ascii_comp_enc = AsciiCompatibleEncoding::new(enc).unwrap();

    let mut rewriter = HtmlRewriter::new(
        Settings {
            encoding: ascii_comp_enc,
            ..Settings::default()
        },
        |buf: &[u8]| { std::io::stdout().write_all(buf).unwrap(); },
    );

    loop {
        if let Err(err) = rewriter.write(&buf) {
            println!("error: {:?}", err);
        }
        if size < buf.len() {
            break;
        }
        size = file.read(&mut buf).unwrap();
    }

    if let Err(err) = rewriter.end() {
        println!("error: {:?}", err);
    }
}
```

Important bits from Cargo.toml
```
[package]
edition = "2018"

[dependencies]
chardetng = "0.1.12"
lol_html = "0.3.0"
```

The simple.html file is available here: https://raw.githubusercontent.com/hadrianw/slimpipe/master/simple.html

The file has a small header and closing body and html tags. In between there are numbers 1 - 65536 separated by spaces with a new line every 16 numbers.

I run with expectation, that diff would be empty:
```
$ cargo run > out.html
$ diff -u simple.html out.html 
--- simple.html 2021-12-10 21:02:07.850715392 +0100
+++ out.html    2021-12-10 21:08:35.282841683 +0100
@@ -4102,4 +4102,75 @@
  65505 65506 65507 65508 65509 65510 65511 65512 65513 65514 65515 65516 65517 65518 65519 65520
  65521 65522 65523 65524 65525 65526 65527 65528 65529 65530 65531 65532 65533 65534 65535 65536
 </body>
-</html>
\ No newline at end of file
+</html>4188 64189 64190 64191 64192
+ 64193 64194 64195 64196 64197 64198 64199 64200 64201 64202 64203 64204 64205 64206 64207 64208
+ 64209 64210 64211 64212 64213 64214 64215 64216 64217 64218 64219 64220 64221 64222 64223 64224
+ 64225 64226 64227 64228 64229 64230 64231 64232 64233 64234 64235 64236 64237 64238 64239 64240
+ 64241 64242 64243 64244 64245 64246 64247 64248 64249 64250 64251 64252 64253 64254 64255 64256
+ 64257 64258 64259 64260 64261 64262 64263 64264 64265 64266 64267 64268 64269 64270 64271 64272
+ 64273 64274 64275 64276 64277 64278 64279 64280 64281 64282 64283 64284 64285 64286 64287 64288
+ 64289 64290 64291 64292 64293 64294 64295 64296 64297 64298 64299 64300 64301 64302 64303 64304
+ 64305 64306 64307 64308 64309 64310 64311 64312 64313 64314 64315 64316 64317 64318 64319 64320
+ 64321 64322 64323 64324 64325 64326 64327 64328 64329 64330 64331 64332 64333 64334 64335 64336
+ 64337 64338 64339 64340 64341 64342 64343 64344 64345 64346 64347 64348 64349 64350 64351 64352
+ 64353 64354 64355 64356 64357 64358 64359 64360 64361 64362 64363 64364 64365 64366 64367 64368
+ 64369 64370 64371 64372 64373 64374 64375 64376 64377 64378 64379 64380 64381 64382 64383 64384
+ 64385 64386 64387 64388 64389 64390 64391 64392 64393 64394 64395 64396 64397 64398 64399 64400
+ 64401 64402 64403 64404 64405 64406 64407 64408 64409 64410 64411 64412 64413 64414 64415 64416
+ 64417 64418 64419 64420 64421 64422 64423 64424 64425 64426 64427 64428 64429 64430 64431 64432
+ 64433 64434 64435 64436 64437 64438 64439 64440 64441 64442 64443 64444 64445 64446 64447 64448
+ 64449 64450 64451 64452 64453 64454 64455 64456 64457 64458 64459 64460 64461 64462 64463 64464
+ 64465 64466 64467 64468 64469 64470 64471 64472 64473 64474 64475 64476 64477 64478 64479 64480
+ 64481 64482 64483 64484 64485 64486 64487 64488 64489 64490 64491 64492 64493 64494 64495 64496
+ 64497 64498 64499 64500 64501 64502 64503 64504 64505 64506 64507 64508 64509 64510 64511 64512
+ 64513 64514 64515 64516 64517 64518 64519 64520 64521 64522 64523 64524 64525 64526 64527 64528
+ 64529 64530 64531 64532 64533 64534 64535 64536 64537 64538 64539 64540 64541 64542 64543 64544
+ 64545 64546 64547 64548 64549 64550 64551 64552 64553 64554 64555 64556 64557 64558 64559 64560
+ 64561 64562 64563 64564 64565 64566 64567 64568 64569 64570 64571 64572 64573 64574 64575 64576
+ 64577 64578 64579 64580 64581 64582 64583 64584 64585 64586 64587 64588 64589 64590 64591 64592
+ 64593 64594 64595 64596 64597 64598 64599 64600 64601 64602 64603 64604 64605 64606 64607 64608
+ 64609 64610 64611 64612 64613 64614 64615 64616 64617 64618 64619 64620 64621 64622 64623 64624
+ 64625 64626 64627 64628 64629 64630 64631 64632 64633 64634 64635 64636 64637 64638 64639 64640
+ 64641 64642 64643 64644 64645 64646 64647 64648 64649 64650 64651 64652 64653 64654 64655 64656
+ 64657 64658 64659 64660 64661 64662 64663 64664 64665 64666 64667 64668 64669 64670 64671 64672
+ 64673 64674 64675 64676 64677 64678 64679 64680 64681 64682 64683 64684 64685 64686 64687 64688
+ 64689 64690 64691 64692 64693 64694 64695 64696 64697 64698 64699 64700 64701 64702 64703 64704
+ 64705 64706 64707 64708 64709 64710 64711 64712 64713 64714 64715 64716 64717 64718 64719 64720
+ 64721 64722 64723 64724 64725 64726 64727 64728 64729 64730 64731 64732 64733 64734 64735 64736
+ 64737 64738 64739 64740 64741 64742 64743 64744 64745 64746 64747 64748 64749 64750 64751 64752
+ 64753 64754 64755 64756 64757 64758 64759 64760 64761 64762 64763 64764 64765 64766 64767 64768
+ 64769 64770 64771 64772 64773 64774 64775 64776 64777 64778 64779 64780 64781 64782 64783 64784
+ 64785 64786 64787 64788 64789 64790 64791 64792 64793 64794 64795 64796 64797 64798 64799 64800
+ 64801 64802 64803 64804 64805 64806 64807 64808 64809 64810 64811 64812 64813 64814 64815 64816
+ 64817 64818 64819 64820 64821 64822 64823 64824 64825 64826 64827 64828 64829 64830 64831 64832
+ 64833 64834 64835 64836 64837 64838 64839 64840 64841 64842 64843 64844 64845 64846 64847 64848
+ 64849 64850 64851 64852 64853 64854 64855 64856 64857 64858 64859 64860 64861 64862 64863 64864
+ 64865 64866 64867 64868 64869 64870 64871 64872 64873 64874 64875 64876 64877 64878 64879 64880
+ 64881 64882 64883 64884 64885 64886 64887 64888 64889 64890 64891 64892 64893 64894 64895 64896
+ 64897 64898 64899 64900 64901 64902 64903 64904 64905 64906 64907 64908 64909 64910 64911 64912
+ 64913 64914 64915 64916 64917 64918 64919 64920 64921 64922 64923 64924 64925 64926 64927 64928
+ 64929 64930 64931 64932 64933 64934 64935 64936 64937 64938 64939 64940 64941 64942 64943 64944
+ 64945 64946 64947 64948 64949 64950 64951 64952 64953 64954 64955 64956 64957 64958 64959 64960
+ 64961 64962 64963 64964 64965 64966 64967 64968 64969 64970 64971 64972 64973 64974 64975 64976
+ 64977 64978 64979 64980 64981 64982 64983 64984 64985 64986 64987 64988 64989 64990 64991 64992
+ 64993 64994 64995 64996 64997 64998 64999 65000 65001 65002 65003 65004 65005 65006 65007 65008
+ 65009 65010 65011 65012 65013 65014 65015 65016 65017 65018 65019 65020 65021 65022 65023 65024
+ 65025 65026 65027 65028 65029 65030 65031 65032 65033 65034 65035 65036 65037 65038 65039 65040
+ 65041 65042 65043 65044 65045 65046 65047 65048 65049 65050 65051 65052 65053 65054 65055 65056
+ 65057 65058 65059 65060 65061 65062 65063 65064 65065 65066 65067 65068 65069 65070 65071 65072
+ 65073 65074 65075 65076 65077 65078 65079 65080 65081 65082 65083 65084 65085 65086 65087 65088
+ 65089 65090 65091 65092 65093 65094 65095 65096 65097 65098 65099 65100 65101 65102 65103 65104
+ 65105 65106 65107 65108 65109 65110 65111 65112 65113 65114 65115 65116 65117 65118 65119 65120
+ 65121 65122 65123 65124 65125 65126 65127 65128 65129 65130 65131 65132 65133 65134 65135 65136
+ 65137 65138 65139 65140 65141 65142 65143 65144 65145 65146 65147 65148 65149 65150 65151 65152
+ 65153 65154 65155 65156 65157 65158 65159 65160 65161 65162 65163 65164 65165 65166 65167 65168
+ 65169 65170 65171 65172 65173 65174 65175 65176 65177 65178 65179 65180 65181 65182 65183 65184
+ 65185 65186 65187 65188 65189 65190 65191 65192 65193 65194 65195 65196 65197 65198 65199 65200
+ 65201 65202 65203 65204 65205 65206 65207 65208 65209 65210 65211 65212 65213 65214 65215 65216
+ 65217 65218 65219 65220 65221 65222 65223 65224 65225 65226 65227 65228 65229 65230 65231 65232
+ 65233 65234 65235 65236 65237 65238 65239 65240 65241 65242 65243 65244 65245 65246 65247 65248
+ 65249 65250 65251 65252 65253 65254 65255 65256 65257 65258 65259 65260 65261 65262 65263 65264
+ 65265 65266 65267 65268 65269 65270 65271 65272 65273 65274 65275 65276 65277 65278 65279 65280
+ 65281 65282 65283 65284 65285 65286 65287 65288 65289 65290 65291 65292 65293 65294 65295 65296
+ 65297 65298 65299 65300 65301 65302 65303 65304 65305 65306 65307 65308 65309 65310 65311 65312
+ 65313 65314 65315 65316 65317 65318 65319 65320 65321 65322 65323 65324 65325
\ No newline at end of file
```

Do I do something wrong or is it a bug?

**Comment by jongiddy** [comment] 2021-12-16 21:51
It looks like the problem is with:
```rust
    loop {
        if let Err(err) = rewriter.write(&buf) {
            println!("error: {:?}", err);
        }
        if size < buf.len() {
            break;
        }
        size = file.read(&mut buf).unwrap();
    }
```
You are reading chunks of 8192 bytes and feeding them into the rewriter. But the last chunk is likely to be less than 8192 bytes, making `size < buf.len()` true. Before you break out of the loop, you send this last buffer to the rewriter. However, `buf` doesn't know about `size`. So you're sending the full buffer of size 8192 into the rewriter. The first part of this buffer contains the final values from the file, but the second part still contains the values from the previous read.

It should work correctly if you change it to the first line in the loop to use `rewriter.write(&buf[..size])`.

**Comment by jyn514** [comment] 2021-12-16 21:54
Alternatively, you could use `read_all` instead of `read`.

Closing since this isn't a lol-html bug.

**Closed by jyn514** 2021-12-16 21:54 UTC

**Comment by hadrianw** [comment] 2021-12-17 12:40
Thank you. Sorry for bothering you, I'm still quite fresh with Rust.

**Comment by jyn514** [comment] 2021-12-17 12:41
No worries! Good luck learning Rust :)
